export const FIXED_DT = 1 / 60;

export const GAME_CONFIG = {
    arenaHalfSize: 34,
    playerHeight: 1.72,
    playerRadius: 0.65,
    maxHealth: 100,
    maxStamina: 100,
    maxAmmo: 30,
    maxReserveAmmo: 240,
    startingReserveAmmo: 180,
    walkSpeed: 7.8,
    sprintSpeed: 12.2,
    sprintDrain: 38,
    staminaRegen: 26,
    reloadDuration: 1.4,
    fireRate: 8.5,
    bulletDamage: 18,
    bulletRange: 72,
    bulletSpread: 0.0125,
    meleeCooldown: 0.72,
    meleeRange: 3.3,
    meleeDamage: 18,
    meleePush: 8,
    damageShake: 0.3,
    explosionShake: 0.5,
    comboWindow: 3.4,
    waveDelay: 2.8,
    pickupRadius: 1.65,
    lowHealthThreshold: 33,
};

export const ENEMY_TYPES = {
    shambler: {
        id: "shambler",
        label: "Shambler",
        health: 36,
        speed: 2.1,
        radius: 0.72,
        damage: 10,
        attackCooldown: 0.95,
        score: 100,
        color: 0x6d8e44,
        emissive: 0x9ddc49,
        dropChance: 0.28,
    },
    runner: {
        id: "runner",
        label: "Runner",
        health: 24,
        speed: 4.35,
        radius: 0.58,
        damage: 8,
        attackCooldown: 0.72,
        score: 150,
        color: 0xbc5148,
        emissive: 0xff8b5d,
        dropChance: 0.34,
    },
    brute: {
        id: "brute",
        label: "Brute",
        health: 320,
        speed: 1.75,
        radius: 1.05,
        damage: 20,
        attackCooldown: 1.24,
        score: 1200,
        color: 0x3f5965,
        emissive: 0x8fdcff,
        dropChance: 1,
    },
};

export const PICKUP_TYPES = {
    ammo: {
        id: "ammo",
        label: "Ammo Crate",
        amount: 45,
    },
    medkit: {
        id: "medkit",
        label: "Med Kit",
        amount: 28,
    },
    charge: {
        id: "charge",
        label: "Adrenal Charge",
        amount: 42,
    },
};

export const WAVE_CONFIGS = [
    {
        wave: 1,
        banner: "Wave 1",
        subtitle: "Contain the first breach",
        spawnInterval: 1.15,
        composition: { shambler: 8 },
    },
    {
        wave: 2,
        banner: "Wave 2",
        subtitle: "Runners on the flank",
        spawnInterval: 0.95,
        composition: { shambler: 8, runner: 4 },
    },
    {
        wave: 3,
        banner: "Wave 3",
        subtitle: "Barrels armed. Burn the lane.",
        spawnInterval: 0.88,
        composition: { shambler: 10, runner: 6 },
    },
    {
        wave: 4,
        banner: "Wave 4",
        subtitle: "Yard overrun. Keep the route open.",
        spawnInterval: 0.78,
        composition: { shambler: 14, runner: 8 },
    },
    {
        wave: 5,
        banner: "Wave 5",
        subtitle: "Brute signature detected",
        spawnInterval: 0.74,
        composition: { shambler: 8, runner: 10, brute: 1 },
    },
];
